task:
  name: "FreeBsd 12.1 amd64  [GOAL: install]  [no depends, only system libs]"
  freebsd_instance:
    image_family: freebsd-12-1  # https://cirrus-ci.org/guide/FreeBSD/
    cpu: 8
    memory: 8G
  timeout_in: 60m
  env:
    MAKEJOBS: "-j9"
    CONFIGURE_OPTS: "--disable-dependency-tracking"
    GOAL: "install"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_COMPRESS: 1
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  install_script:
    - pkg install -y autoconf automake boost-libs git gmake libevent libtool pkgconf python3 ccache
    - ./contrib/install_db4.sh $(pwd)
    - ccache --max-size=${CCACHE_SIZE}
  configure_script:
    - ./autogen.sh
    - ./configure ${CONFIGURE_OPTS} BDB_LIBS="-L$(pwd)/db4/lib -ldb_cxx-4.8" BDB_CFLAGS="-I$(pwd)/db4/include" || ( cat config.log && false)
  make_script:
    - gmake ${MAKEJOBS} ${GOAL} || ( echo "Build failure. Verbose build follows." && gmake ${GOAL} V=1 ; false )
  check_script:
    - gmake check ${MAKEJOBS} VERBOSE=1
  functional_test_script:
    - ./test/functional/test_runner.py --jobs 9 --ci --extended --exclude feature_dbcrash,feature_pruning,feature_block --combinedlogslen=1000 --quiet --failfast --ghost --insight --bitcoin
#task:
#  name: "Windows"
#  windows_container:
#    image: cirrusci/windowsservercore:2019
#  env:
#    CIRRUS_SHELL: powershell
#    PATH: 'C:\Python37;C:\Python37\Scripts;%PATH%'
#    PYTHONUTF8: 1
#    QT_DOWNLOAD_URL: 'https://github.com/sipsorcery/qt_win_binary/releases/download/v1.6/Qt5.9.8_x64_static_vs2019.zip'
#    QT_DOWNLOAD_HASH: '9a8c6eb20967873785057fdcd329a657c7f922b0af08c5fde105cc597dd37e21'
#    QT_LOCAL_PATH: 'C:\Qt5.9.8_x64_static_vs2019'
#    VCPKG_INSTALL_PATH: 'C:\tools\vcpkg\installed'
#    VCPKG_COMMIT_ID: 'ed0df8ecc4ed7e755ea03e18aaf285fd9b4b4a74'
#  install_script:
#    - choco install python --version=3.7.7 -y
task:
  name: "x86_64 Linux  [GOAL: install]  [bionic]  [Using ./ci/ system]"
  container:
    image: ubuntu:18.04
    cpu: 8
    memory: 8G
  timeout_in: 60m
  env:
    MAKEJOBS: "-j9"
    DANGER_RUN_CI_ON_HOST: "1"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  depends_built_cache:
    folder: "/tmp/cirrus-ci-build/depends/built"
  install_script:
    - apt-get update
    - apt-get -y install git bash ccache libudev-dev
    - ccache --max-size=${CCACHE_SIZE}
  ci_script:
    - ./ci/test_run_all.sh
