#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the ghost network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    //TODO GHOSTFORK fill mainnet seeds once we have them
};

static SeedSpec6 pnSeed6_test[] = {
    //TODO GHOSTFORK fill testnet seeds once we have them
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
